### ISSUE TITLE
Composition API & Typescript migration

### ISSUE THREAD

**Issue by Mysterious-Dev** [modrinth/omorphia#153]
This issue is related to the migration of omorphia components to the composition API and/or Typescript.

### Base

- [x] Chips [4856a6aefccf9019c0a2670cc2c1f57222feb6ef]
- [x] FileInput [4856a6aefccf9019c0a2670cc2c1f57222feb6ef]
- [x] ProjectCard [4856a6aefccf9019c0a2670cc2c1f57222feb6ef]
- [x] Toogle [4856a6aefccf9019c0a2670cc2c1f57222feb6ef]
- [x] NavRow [4856a6aefccf9019c0a2670cc2c1f57222feb6ef]

### Base

- [ ] Avatar [#149]
- [ ] Badge [#130]
- [ ] Button [#150]
- [ ] Chips [#154]
- [ ] ConditionalNuxtLink [#152]
- [ ] DropdownSelect
- [ ] FileInput
- [ ] Notifications
- [ ] OverflowMenu
- [ ] Page [#155]
- [ ] PopoutMenu [#160]
- [ ] ProjectCard [#156]
- [ ] Toogle [#145]

### Chart

- [ ] Chart
- [ ] CompactChart

### Modal

- [ ] ConfirmModal [#157]
- [ ] Modal
- [ ] ReportModal
- [ ] ShareModal

### Navigation

- [ ] Breadcrumbs
- [ ] NavItem
- [ ] NavRow

### Search

- [ ] Categories
- [ ] SearchDropdown
- [ ] SearchFilter

**Comment by brawaru** [comment]
@Arthur-GYT do you mind moving this to the new monorepo (https://github.com/modrinth/code)? :)

**Comment by Arthur-GYT** [comment]
Done ^^
